package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"reflect"
	"strings"
	"text/template"
)

type Field struct {
	Name         string
	Type         string
	DBName       string
	IsPrimaryKey bool
}

type Relation struct {
	FieldName    string
	TargetModel  string
	ForeignKey   string
	TargetTable  string
	TargetFKName string
	RelType      string
}

type Model struct {
	Name                        string
	TableName                   string
	Fields                      []Field
	Relations                   []Relation
	InsertColumns               string
	InsertPlaceholders          string
	InsertArgs                  string
	UpdateColumns               string
	UpdateArgs                  string
	UpsertColumns               string
	PrimaryKeyColumn            string
	PrimaryKeyName              string
	PrimaryKeyType              string
	UpdatePrimaryKeyPlaceholder string
	CreateTableSQL              string
	CopyFromColumns             string
}

// toPascalCase converts snake_case to PascalCase (e.g. user_id -> UserID)
func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if strings.ToLower(p) == "id" {
			parts[i] = "ID"
		} else if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + strings.ToLower(p[1:])
		}
	}
	return strings.Join(parts, "")
}

const whisperTemplate = `// Code generated by Whisper ORM. DO NOT EDIT.
package {{.PackageName}}

import (
	"context"
	"github.com/jackc/pgx/v5"
	"github.com/bdrtr/hush/whisper"
)

{{range .Models}}
// CreateTable creates the table for the {{.Name}} model if it does not exist.
func (m *{{.Name}}) CreateTable(ctx context.Context, q whisper.Queryable) error {
	query := ` + "`" + `{{.CreateTableSQL}}` + "`" + `
	_, err := q.Exec(ctx, query)
	return err
}

// ScanRow scans a single database row into the {{.Name}} model.
func (m *{{.Name}}) ScanRow(row pgx.Row) error {
	return row.Scan(
		{{range .Fields}}&m.{{.Name}},
		{{end}}
	)
}

// ScanRows scans multiple database rows into a slice of {{.Name}}.
func Scan{{.Name}}Rows(rows pgx.Rows) ([]{{.Name}}, error) {
	var results []{{.Name}}
	for rows.Next() {
		var m {{.Name}}
		if err := rows.Scan(
			{{range .Fields}}&m.{{.Name}},
			{{end}}
		); err != nil {
			return nil, err
		}
		results = append(results, m)
	}
	return results, nil
}

// Insert executes a zero-allocation INSERT query for the {{.Name}} model.
func (m *{{.Name}}) Insert(ctx context.Context, q whisper.Queryable) error {
	query := "INSERT INTO {{.TableName}} ({{.InsertColumns}}) VALUES ({{.InsertPlaceholders}})"
	_, err := q.Exec(ctx, query, {{.InsertArgs}})
	return err
}

// InsertBulk uses PostgreSQL native COPY protocol for high-performance bulk inserts.
func InsertBulk{{.Name}}(ctx context.Context, q whisper.Queryable, items []{{.Name}}) (int64, error) {
	rows := make([][]any, len(items))
	for i, m := range items {
		rows[i] = []any{ {{.InsertArgs}} }
	}
	
	count, err := q.CopyFrom(
		ctx,
		pgx.Identifier{"{{.TableName}}"},
		[]string{ {{.CopyFromColumns}} },
		pgx.CopyFromRows(rows),
	)
	return count, err
}

// Update executes a zero-allocation UPDATE query for the {{.Name}} model using its primary key.
func (m *{{.Name}}) Update(ctx context.Context, q whisper.Queryable) error {
	query := "UPDATE {{.TableName}} SET {{.UpdateColumns}} WHERE {{.PrimaryKeyColumn}} = {{.UpdatePrimaryKeyPlaceholder}}"
	_, err := q.Exec(ctx, query, {{.UpdateArgs}}, m.{{.PrimaryKeyName}})
	return err
}

// Delete executes a zero-allocation DELETE query for the {{.Name}} model.
func (m *{{.Name}}) Delete(ctx context.Context, q whisper.Queryable) error {
	query := "DELETE FROM {{.TableName}} WHERE {{.PrimaryKeyColumn}} = $1"
	_, err := q.Exec(ctx, query, m.{{.PrimaryKeyName}})
	return err
}

// Upsert inserts the {{.Name}} model or updates it if a conflict on the primary key occurs.
// Uses PostgreSQL EXCLUDED keyword to reference the conflicting row's values.
func (m *{{.Name}}) Upsert(ctx context.Context, q whisper.Queryable) error {
	query := "INSERT INTO {{.TableName}} ({{.InsertColumns}}) VALUES ({{.InsertPlaceholders}}) ON CONFLICT ({{.PrimaryKeyColumn}}) DO UPDATE SET {{.UpsertColumns}}"
	_, err := q.Exec(ctx, query, {{.InsertArgs}})
	return err
}

{{$modelName := .Name}}
{{$pkName := .PrimaryKeyName}}
{{$pkType := .PrimaryKeyType}}
{{range .Relations}}
{{if eq .RelType "has_many"}}
// Load{{.FieldName}} fetches the related {{.TargetModel}} entities for {{$modelName}}.
func (m *{{$modelName}}) Load{{.FieldName}}(ctx context.Context, q whisper.Queryable) error {
	query := "SELECT id, user_id, name, price FROM {{.TargetTable}} WHERE {{.ForeignKey}} = $1"
	rows, err := q.Query(ctx, query, m.{{$pkName}})
	if err != nil {
		return err
	}
	defer rows.Close()

	results, err := Scan{{.TargetModel}}Rows(rows)
	if err != nil {
		return err
	}
	m.{{.FieldName}} = results
	return nil
}

// Load{{.FieldName}}Batch (DataLoader Pattern) fetches related {{.TargetModel}} entities for a batch of {{$modelName}}s using a single query (N+1 solver).
func Load{{.FieldName}}Batch(ctx context.Context, q whisper.Queryable, items []*{{$modelName}}) error {
	if len(items) == 0 {
		return nil
	}

	ids := make([]{{$pkType}}, len(items))
	for i, item := range items {
		ids[i] = item.{{$pkName}}
	}

	// Postgres ANY() operatörü ile tek sorguda toplu çekim
	query := "SELECT id, user_id, name, price FROM {{.TargetTable}} WHERE {{.ForeignKey}} = ANY($1)"
	rows, err := q.Query(ctx, query, ids)
	if err != nil {
		return err
	}
	defer rows.Close()

	results, err := Scan{{.TargetModel}}Rows(rows)
	if err != nil {
		return err
	}

	// Hafızada eşleştirme (O(N) karmaşıklık)
	relMap := make(map[{{$pkType}}][]{{.TargetModel}})
	for _, res := range results {
		key := res.{{.TargetFKName}}
		relMap[key] = append(relMap[key], res)
	}

	for _, item := range items {
		item.{{.FieldName}} = relMap[item.{{$pkName}}]
	}

	return nil
}
{{end}}
{{end}}
{{end}}
`

func main() {
	var filename string
	flag.StringVar(&filename, "file", "", "Go file to parse")
	flag.Parse()

	if filename == "" {
		log.Fatal("Lütfen parse edilecek dosyayı -file parametresi ile belirtin.")
	}

	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
	if err != nil {
		log.Fatal(err)
	}

	packageName := node.Name.Name
	var models []Model

	ast.Inspect(node, func(n ast.Node) bool {
		typeDecl, ok := n.(*ast.TypeSpec)
		if !ok {
			return true
		}

		structType, ok := typeDecl.Type.(*ast.StructType)
		if !ok {
			return true
		}

		modelName := typeDecl.Name.Name
		model := Model{
			Name:      modelName,
			TableName: strings.ToLower(modelName) + "s",
		}

		for _, field := range structType.Fields.List {
			if len(field.Names) == 0 {
				continue
			}
			fieldName := field.Names[0].Name
			
			fieldType := ""
			switch t := field.Type.(type) {
			case *ast.Ident:
				fieldType = t.Name
			case *ast.SelectorExpr:
				if ident, ok := t.X.(*ast.Ident); ok {
					fieldType = ident.Name + "." + t.Sel.Name
				}
			case *ast.StarExpr:
				if ident, ok := t.X.(*ast.Ident); ok {
					fieldType = "*" + ident.Name
				}
			}

			dbName := strings.ToLower(fieldName)
			isPk := false
			isIgnored := false
			
			if field.Tag != nil {
				tagValue := strings.Trim(field.Tag.Value, "`")
				tag := reflect.StructTag(tagValue)
				
				if dbTag, ok := tag.Lookup("db"); ok {
					if dbTag == "-" {
						isIgnored = true
					} else {
						parts := strings.Split(dbTag, ",")
						if parts[0] != "" {
							dbName = parts[0]
						}
						for _, part := range parts[1:] {
							if part == "primary_key" {
								isPk = true
							}
						}
					}
				}

				if whisperTag, ok := tag.Lookup("whisper"); ok && isIgnored {
					parts := strings.Split(whisperTag, ",")
					relTypePart := strings.Split(parts[0], ":")
					
					if len(relTypePart) == 2 {
						relType := relTypePart[0]
						targetModel := relTypePart[1]
						targetTable := strings.ToLower(targetModel) + "s"
						
						fk := ""
						if len(parts) > 1 && strings.HasPrefix(parts[1], "fk:") {
							fk = strings.TrimPrefix(parts[1], "fk:")
						}
						
						targetFkName := toPascalCase(fk)

						model.Relations = append(model.Relations, Relation{
							FieldName:    fieldName,
							TargetModel:  targetModel,
							TargetTable:  targetTable,
							ForeignKey:   fk,
							TargetFKName: targetFkName,
							RelType:      relType,
						})
					}
				}
			}

			if isIgnored {
				continue
			}

			if isPk || (len(model.Fields) == 0 && strings.ToUpper(fieldName) == "ID") {
				isPk = true
				model.PrimaryKeyColumn = dbName
				model.PrimaryKeyName = fieldName
				model.PrimaryKeyType = fieldType
			}

			model.Fields = append(model.Fields, Field{
				Name:         fieldName,
				Type:         fieldType,
				DBName:       dbName,
				IsPrimaryKey: isPk,
			})
		}
		
		var insCols, insArgs, updCols, updArgs, upsertCols []string
		var createCols []string
		updPlaceholderIndex := 1

		for _, f := range model.Fields {
			insCols = append(insCols, f.DBName)
			insArgs = append(insArgs, "m."+f.Name)
			
			if !f.IsPrimaryKey {
				updCols = append(updCols, fmt.Sprintf("%s = $%d", f.DBName, updPlaceholderIndex))
				updArgs = append(updArgs, "m."+f.Name)
				updPlaceholderIndex++

				// Upsert için EXCLUDED keyword'ünü kullanarak placeholder sorununu ortadan kaldır
				upsertCols = append(upsertCols, fmt.Sprintf("%s = EXCLUDED.%s", f.DBName, f.DBName))
			}

			sqlType := "VARCHAR(255)"
			switch f.Type {
			case "int", "int64", "int32":
				if f.IsPrimaryKey {
					sqlType = "SERIAL PRIMARY KEY"
				} else {
					sqlType = "INT"
				}
			case "string":
				sqlType = "VARCHAR(255)"
			case "bool":
				sqlType = "BOOLEAN"
			case "float64", "float32":
				sqlType = "DOUBLE PRECISION"
			case "time.Time", "*time.Time":
				sqlType = "TIMESTAMP"
			}

			if f.IsPrimaryKey && !strings.Contains(sqlType, "PRIMARY KEY") {
				sqlType += " PRIMARY KEY"
			}

			createCols = append(createCols, fmt.Sprintf("%s %s", f.DBName, sqlType))
		}

		var insPlaceholders []string
		var copyCols []string
		for i, col := range insCols {
			insPlaceholders = append(insPlaceholders, fmt.Sprintf("$%d", i+1))
			copyCols = append(copyCols, fmt.Sprintf(`"%s"`, col))
		}

		model.InsertColumns = strings.Join(insCols, ", ")
		model.InsertPlaceholders = strings.Join(insPlaceholders, ", ")
		model.InsertArgs = strings.Join(insArgs, ", ")
		
		model.CopyFromColumns = strings.Join(copyCols, ", ")

		model.UpdateColumns = strings.Join(updCols, ", ")
		model.UpdateArgs = strings.Join(updArgs, ", ")
		model.UpsertColumns = strings.Join(upsertCols, ", ")
		model.UpdatePrimaryKeyPlaceholder = fmt.Sprintf("$%d", updPlaceholderIndex)

		model.CreateTableSQL = fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n\t\t%s\n\t)", model.TableName, strings.Join(createCols, ",\n\t\t"))

		models = append(models, model)
		return false
	})

	tmpl, err := template.New("whisper").Parse(whisperTemplate)
	if err != nil {
		log.Fatalf("Template parse hatası: %v", err)
	}

	var buf bytes.Buffer
	data := struct {
		PackageName string
		Models      []Model
	}{
		PackageName: packageName,
		Models:      models,
	}

	if err := tmpl.Execute(&buf, data); err != nil {
		log.Fatalf("Template execute hatası: %v", err)
	}

	formattedSource, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("Format hatası: %v\n\n%s", err, buf.String())
	}

	outFilename := strings.TrimSuffix(filename, ".go") + "_whisper.go"
	err = os.WriteFile(outFilename, formattedSource, 0644)
	if err != nil {
		log.Fatalf("Dosya yazma hatası: %v", err)
	}

	fmt.Printf("Whisper ORM DataLoader/Batch metodu eklendi!\n")
}
