// Code generated by Whisper ORM. DO NOT EDIT.
package models

import (
	"context"
	"github.com/bdrtr/hush/whisper"
	"github.com/jackc/pgx/v5"
)

// CreateTable creates the table for the User model if it does not exist.
func (m *User) CreateTable(ctx context.Context, q whisper.Queryable) error {
	query := `CREATE TABLE IF NOT EXISTS users (
		user_id SERIAL PRIMARY KEY,
		username VARCHAR(255),
		email VARCHAR(255),
		password_hash VARCHAR(255),
		is_active BOOLEAN,
		created_at TIMESTAMP
	)`
	_, err := q.Exec(ctx, query)
	return err
}

// ScanRow scans a single database row into the User model.
func (m *User) ScanRow(row pgx.Row) error {
	return row.Scan(
		&m.ID,
		&m.Username,
		&m.Email,
		&m.Password,
		&m.IsActive,
		&m.CreatedAt,
	)
}

// ScanRows scans multiple database rows into a slice of User.
func ScanUserRows(rows pgx.Rows) ([]User, error) {
	var results []User
	for rows.Next() {
		var m User
		if err := rows.Scan(
			&m.ID,
			&m.Username,
			&m.Email,
			&m.Password,
			&m.IsActive,
			&m.CreatedAt,
		); err != nil {
			return nil, err
		}
		results = append(results, m)
	}
	return results, nil
}

// Insert executes a zero-allocation INSERT query for the User model.
func (m *User) Insert(ctx context.Context, q whisper.Queryable) error {
	query := "INSERT INTO users (user_id, username, email, password_hash, is_active, created_at) VALUES ($1, $2, $3, $4, $5, $6)"
	_, err := q.Exec(ctx, query, m.ID, m.Username, m.Email, m.Password, m.IsActive, m.CreatedAt)
	return err
}

// InsertBulk uses PostgreSQL native COPY protocol for high-performance bulk inserts.
func InsertBulkUser(ctx context.Context, q whisper.Queryable, items []User) (int64, error) {
	rows := make([][]any, len(items))
	for i, m := range items {
		rows[i] = []any{m.ID, m.Username, m.Email, m.Password, m.IsActive, m.CreatedAt}
	}

	count, err := q.CopyFrom(
		ctx,
		pgx.Identifier{"users"},
		[]string{"user_id", "username", "email", "password_hash", "is_active", "created_at"},
		pgx.CopyFromRows(rows),
	)
	return count, err
}

// Update executes a zero-allocation UPDATE query for the User model using its primary key.
func (m *User) Update(ctx context.Context, q whisper.Queryable) error {
	query := "UPDATE users SET username = $1, email = $2, password_hash = $3, is_active = $4, created_at = $5 WHERE user_id = $6"
	_, err := q.Exec(ctx, query, m.Username, m.Email, m.Password, m.IsActive, m.CreatedAt, m.ID)
	return err
}

// Delete executes a zero-allocation DELETE query for the User model.
func (m *User) Delete(ctx context.Context, q whisper.Queryable) error {
	query := "DELETE FROM users WHERE user_id = $1"
	_, err := q.Exec(ctx, query, m.ID)
	return err
}

// Upsert inserts the User model or updates it if a conflict on the primary key occurs.
// Uses PostgreSQL EXCLUDED keyword to reference the conflicting row's values.
func (m *User) Upsert(ctx context.Context, q whisper.Queryable) error {
	query := "INSERT INTO users (user_id, username, email, password_hash, is_active, created_at) VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT (user_id) DO UPDATE SET username = EXCLUDED.username, email = EXCLUDED.email, password_hash = EXCLUDED.password_hash, is_active = EXCLUDED.is_active, created_at = EXCLUDED.created_at"
	_, err := q.Exec(ctx, query, m.ID, m.Username, m.Email, m.Password, m.IsActive, m.CreatedAt)
	return err
}

// LoadProducts fetches the related Product entities for User.
func (m *User) LoadProducts(ctx context.Context, q whisper.Queryable) error {
	query := "SELECT id, user_id, name, price FROM products WHERE user_id = $1"
	rows, err := q.Query(ctx, query, m.ID)
	if err != nil {
		return err
	}
	defer rows.Close()

	results, err := ScanProductRows(rows)
	if err != nil {
		return err
	}
	m.Products = results
	return nil
}

// LoadProductsBatch (DataLoader Pattern) fetches related Product entities for a batch of Users using a single query (N+1 solver).
func LoadProductsBatch(ctx context.Context, q whisper.Queryable, items []*User) error {
	if len(items) == 0 {
		return nil
	}

	ids := make([]int, len(items))
	for i, item := range items {
		ids[i] = item.ID
	}

	// Postgres ANY() operatörü ile tek sorguda toplu çekim
	query := "SELECT id, user_id, name, price FROM products WHERE user_id = ANY($1)"
	rows, err := q.Query(ctx, query, ids)
	if err != nil {
		return err
	}
	defer rows.Close()

	results, err := ScanProductRows(rows)
	if err != nil {
		return err
	}

	// Hafızada eşleştirme (O(N) karmaşıklık)
	relMap := make(map[int][]Product)
	for _, res := range results {
		key := res.UserID
		relMap[key] = append(relMap[key], res)
	}

	for _, item := range items {
		item.Products = relMap[item.ID]
	}

	return nil
}

// CreateTable creates the table for the Product model if it does not exist.
func (m *Product) CreateTable(ctx context.Context, q whisper.Queryable) error {
	query := `CREATE TABLE IF NOT EXISTS products (
		id SERIAL PRIMARY KEY,
		user_id INT,
		name VARCHAR(255),
		price DOUBLE PRECISION
	)`
	_, err := q.Exec(ctx, query)
	return err
}

// ScanRow scans a single database row into the Product model.
func (m *Product) ScanRow(row pgx.Row) error {
	return row.Scan(
		&m.ID,
		&m.UserID,
		&m.Name,
		&m.Price,
	)
}

// ScanRows scans multiple database rows into a slice of Product.
func ScanProductRows(rows pgx.Rows) ([]Product, error) {
	var results []Product
	for rows.Next() {
		var m Product
		if err := rows.Scan(
			&m.ID,
			&m.UserID,
			&m.Name,
			&m.Price,
		); err != nil {
			return nil, err
		}
		results = append(results, m)
	}
	return results, nil
}

// Insert executes a zero-allocation INSERT query for the Product model.
func (m *Product) Insert(ctx context.Context, q whisper.Queryable) error {
	query := "INSERT INTO products (id, user_id, name, price) VALUES ($1, $2, $3, $4)"
	_, err := q.Exec(ctx, query, m.ID, m.UserID, m.Name, m.Price)
	return err
}

// InsertBulk uses PostgreSQL native COPY protocol for high-performance bulk inserts.
func InsertBulkProduct(ctx context.Context, q whisper.Queryable, items []Product) (int64, error) {
	rows := make([][]any, len(items))
	for i, m := range items {
		rows[i] = []any{m.ID, m.UserID, m.Name, m.Price}
	}

	count, err := q.CopyFrom(
		ctx,
		pgx.Identifier{"products"},
		[]string{"id", "user_id", "name", "price"},
		pgx.CopyFromRows(rows),
	)
	return count, err
}

// Update executes a zero-allocation UPDATE query for the Product model using its primary key.
func (m *Product) Update(ctx context.Context, q whisper.Queryable) error {
	query := "UPDATE products SET user_id = $1, name = $2, price = $3 WHERE id = $4"
	_, err := q.Exec(ctx, query, m.UserID, m.Name, m.Price, m.ID)
	return err
}

// Delete executes a zero-allocation DELETE query for the Product model.
func (m *Product) Delete(ctx context.Context, q whisper.Queryable) error {
	query := "DELETE FROM products WHERE id = $1"
	_, err := q.Exec(ctx, query, m.ID)
	return err
}

// Upsert inserts the Product model or updates it if a conflict on the primary key occurs.
// Uses PostgreSQL EXCLUDED keyword to reference the conflicting row's values.
func (m *Product) Upsert(ctx context.Context, q whisper.Queryable) error {
	query := "INSERT INTO products (id, user_id, name, price) VALUES ($1, $2, $3, $4) ON CONFLICT (id) DO UPDATE SET user_id = EXCLUDED.user_id, name = EXCLUDED.name, price = EXCLUDED.price"
	_, err := q.Exec(ctx, query, m.ID, m.UserID, m.Name, m.Price)
	return err
}
